### ISSUE TITLE
Hey, no idea how to use, thanks

### ISSUE THREAD

**Issue by moehammm** [TheCruZ/Simple-Manual-Map-Injector#10]
Don't know what am I supposed to do, or how can I do it..
No .exe in your files?
Never used visual studio, so I don't know if I have to build the .exe? plus I don't know how to use it :(

**Comment by TheCruZ** [comment]
It's in release section
https://github.com/TheCruZ/Simple-Manual-Map-Injector/releases/tag/V1.1
