### ISSUE TITLE
could you provide full source using byte array instead of a dll file on disk?

### ISSUE THREAD

**Issue by VC1W** [TheCruZ/Simple-Manual-Map-Injector#16]

**Comment by TheCruZ** [comment]
Just set in the source, the code ir already prepared for doing in that way
At https://github.com/TheCruZ/Simple-Manual-Map-Injector/blob/ae4bf482920e8f26ff6fdc99544b27c20b9c5312/Manual%20Map%20Injector/main.cpp#L143C11-L143C11

static unsigned char **fileInMemory**[] = { 0x01, 0x02, 0x03, ... };

if (!ManualMapDll(hProc, **fileInMemory**, 0)) {

literally there is no difference and filesize is not used anymore in the source then not needed and can be 0
