### ISSUE TITLE
About DLL file size cannot be injected

### ISSUE THREAD

**Issue by jackKiZhu** [TheCruZ/Simple-Manual-Map-Injector#2]
I added a VMP, but it will prompt target process memory allocation failed (Ex) error. My DLL file size is about 5MB

**Comment by TheCruZ** [comment]
Well I have packed a hello world DLL, Injected into a process and works fine, file size 5.3 MB

![image](https://user-images.githubusercontent.com/23271181/117551391-ff74aa80-b045-11eb-9449-73c01c4ba03f.png)

**Comment by TheCruZ** [comment]
Closed after some months of inactivity
