### ISSUE TITLE
ROBLOX Crashes when I inject a DLL using this

### ISSUE THREAD

**Issue by RexiRexii** [TheCruZ/Simple-Manual-Map-Injector#6]
I have no idea why, but it just crashes 🤷 
just like CS:GO

**Comment by TheCruZ** [comment]
Did you try with the Hello World dll and no SEH?
If still crash with that is possible that roblox process have patched LoadLibraryA or GetProcAddress

**Comment by RexiRexii** [comment]
> Did you try with the Hello World dll and no SEH? If still crash with that is possible that roblox process have patched LoadLibraryA or GetProcAddress

No, with LoadLibraryA it works just fine
i think it could be my DLL too, i am not sure but I will surely notify you whenever I get actual results

**Comment by RexiRexii** [comment]
Hey, after a while I learned that doing certain stuff can cause the manual mapping to fail
(for instance: using static variables, unless the manual mapper fixes it)
now it works like a charm, good work. Vouch!
